on:
  push:
    branches:
      - dev
      
name: Build
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-12
    
    steps:
      - uses: actions/cache@v2
        id: procache
        with:
          path: |
            ~/__cache
          key: ${{ runner.os }}-procursus
          
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Setup Procursus Bootstrap (install)
        if: steps.procache.outputs.cache-hit != 'true'
        run: |
          wget https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap_darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y || :
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
          sudo /opt/procursus/bin/apt install ldid -y
          
      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          
      - name: Setup Procursus Bootstrap (cache)
        if: steps.procache.outputs.cache-hit == 'true'
        run: |
          sudo mkdir -p ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial
          sudo rsync -aP ~/__cache/procursus /opt
          sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
      
      - name: Select Correct Xcode (13.1)
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.4.1.app
          
      - name: Build Sileo Nightly (iphoneos-arm)
        run: |
          make clean package NIGHTLY=1 DEBUG=0 ALL_BOOTSTRAPS=1
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SileoNightly_iphoneos-arm
          path: packages/*
          
      - name: Copy Procursus to Cache Location
        run: |
          sudo mkdir -p ~/__cache
          sudo rsync -aP /opt/procursus ~/__cache
          sudo rm -rf ~/__cache/procursus/var/cache/apt/archives/partial ~/__cache/procursus/var/lib/apt/lists/partial ~/__cache/procursus/Library/dpkg/triggers/Lock

